[project]
name = "microcontroller-playground"
version = "0.1.0"
description = "The Python environment for the `microcontroller-playground` project"
license = "Apache-2.0"

requires-python = ">=3.10,<4.0"
dependencies = [
    "python-dotenv >=1.1.0",
    "pre-commit >=4.6.2",
    "esptool >=4.8.0",
]
